### ISSUE TITLE
ALLOW pattern doesn't work as expected on windows

### ISSUE THREAD

**Issue by PradyumnaKrishna** [in-toto/in-toto-golang#253]
**General information:**

* Version: latest (0.9.0)
* Operating system: Windows
* Go version: 1.20

**Description of the bug:**
On testing in-toto-golang in windows and running demo against it, I found that in-toto-golang doesn't ALLOWs or ignores subdirs on windows. On running in-toto/demo, the in-toto-golang verify commands doesn't `ALLOW demo-project/.git/*` as provided in layout and fails verification with message disallowed by rule [DISALLOW *].

The logs https://github.com/PradyumnaKrishna/in-toto-testing/actions/runs/5572000137/jobs/10177593630#step:7

```
======================================================================
FAIL: test_using_demo (tests.test_golang.TestGolang)
Test running in-toto demo against in-toto implementations.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\in-toto-testing\in-toto-testing\tests\test_golang.py", line 146, in test_using_demo
    self.assert_cli_sys_exit(verify_cmd_go, 0)
  File "D:\a\in-toto-testing\in-toto-testing\tests\common.py", line 48, in assert_cli_sys_exit
    self.assertEqual(exc.returncode, status, exc.stderr)
AssertionError: 1 != 0 : inspection failed: artifact verification failed for Inspection 'untar', products [
demo-project\.git\packed-refs
demo-project\.git\hooks\fsmonitor-watchman.sample
demo-project\.git\hooks\pre-applypatch.sample
demo-project\.git\logs\refs\remotes\origin\HEAD
demo-project\.git\objects\pack\pack-2c9aff0827d356448f801394c227db42ff9bedb6.pack demo-project\.git\info\exclude
demo-project\.git\description demo-project\.git\hooks\pre-rebase.sample
demo-project\.git\refs\heads\master demo-project\.git\hooks\sendemail-validate.sample
demo-project\.git\hooks\push-to-checkout.sample
demo-project\.git\objects\pack\pack-2c9aff0827d356448f801394c227db42ff9bedb6.rev
demo-project\.git\config demo-project\.git\logs\refs\heads\master
demo-project\.git\hooks\pre-merge-commit.sample
demo-project\.git\hooks\pre-push.sample
demo-project\.git\hooks\post-update.sample
demo-project\.git\objects\pack\pack-2c9aff0827d356448f801394c227db42ff9bedb6.idx
demo-project\.git\hooks\prepare-commit-msg.sample
demo-project\.git\HEAD demo-project\.git\hooks\applypatch-msg.sample
demo-project\.git\hooks\pre-receive.sample demo-project\foo.py
demo-project\.git\refs\remotes\origin\HEAD
demo-project\.git\hooks\commit-msg.sample
demo-project\.git\logs\HEAD demo-project\.git\index
demo-project\.git\hooks\update.sample
demo-project\.git\hooks\pre-commit.sample] disallowed by rule [DISALLOW *]
```

**Anything special you want to tell us?**

**Comment by adityasaky** [comment]
Thanks for identifying this! Looks like we're missing path normalization as the log shows back slashes. Curious why this isn't an issue with the other rules, do you want to take a stab at resolving this?
